### ISSUE TITLE
Inclusão da composição de bandas no resultado final

### ISSUE THREAD

**Issue by victorquaresma** [lmotta/qgis_processing_algorithms#1]
Inclusão da composição de bandas no resultado final do script, ou seja: 

gdal_merge.py -separate -ot Float32 -of GTiff -o /tmp/processing_VdUdfE/ce89dcc7bacf49e3857b9ed5255e6e77/OUTPUT.tif --optfile /tmp/processing_VdUdfE/7287856bb5024bbea3656681a492f3a1/mergeInputFiles.txt

**Comment by lmotta** [comment]
Feito.

A solução foi gerar um Virtual Raster(VRT*), contendo as bandas diferentes de Zero empilhadas.
* https://gdal.org/drivers/raster/vrt.html

**Comment by victorquaresma** [comment]
Obrigado.

Em qua., 7 de out. de 2020 às 09:08, lmotta <notifications@github.com>
escreveu:
